name: Security Check and Encrypt
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  security-check:
    runs-on: windows-latest
    steps:
    - name: Checkout repository
      uses: actions
    - name: Run security check script
      run: # kaspersky
      - name: Run encryption script
      # run: # SHA-256

       - name: Upload encrypted report
      uses: actions/upload-artifact@v3
      with:
        name: encrypted-report
        path: C:\SecurityCheckReport.txt.enc
